include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AccessoryAlertTestPrefs

AccessoryAlertTestPrefs_FILES = AccessoryAlertTestPrefs.m
AccessoryAlertTestPrefs_FRAMEWORKS = UIKit
AccessoryAlertTestPrefs_PRIVATE_FRAMEWORKS = Preferences
AccessoryAlertTestPrefs_INSTALL_PATH = /Library/PreferenceBundles
AccessoryAlertTestPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
