include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FlipOffPrefs

FlipOffPrefs_FILES = FlipOffPrefs.m
FlipOffPrefs_FRAMEWORKS = UIKit
FlipOffPrefs_PRIVATE_FRAMEWORKS = Preferences
FlipOffPrefs_INSTALL_PATH = /Library/PreferenceBundles
FlipOffPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
